### ISSUE TITLE
Some changes you may want to consider

### ISSUE THREAD

**Issue by alanarnholt** [christophergandrud/Rep-Res-Book#58]
Dear Christopher,

Congratulations on the publication of the second edition of Reproducible Research.  I used the first version with a class I taught when it first was published and will be recommending the second edition as supplemental reading in all of my classes.  I made some LaTeX font changes and a few other minor typo/errata changes in a forked version... commit (https://github.com/AppstateWork/Rep-Res-Book/commit/679b426a8a6c4d628ac99e4c6beb5c3ba7fd53a6) ... I imagine CRC would not be excited to make all of the changes for a second printing I have in the commit but I wanted to see what it would look like (and you may as well).  If you are just looking for the typo/errata changes they are on pages 31, 36, 40, 56, 155, 156, 168, 178, 182, and 198 of the book. (The index in my commit does not quite work/look like the book...it seems that commands (\LaTeX, \TeX, etc.) inside footnotes with the function index add an extra space to create two entries...)

Best,
Alan

**Comment by christophergandrud** [comment]
Thanks! And thanks for recommending the second edition to your students.

These changes look great. You're correct that a lot of the formatting was specified by the house style at CRC. I chose not to use `\LaTeX`, etc because as you point out it created a number of odd indexing problems and some people find it tedious to read after a while (though clearly opinions vary!).

Thanks again, and I hope to work in many of the suggestions over the next few days.

Best
Christopher
